export const DEFAULT_PROXY_HOST = "127.0.0.1";
export const DEFAULT_PROXY_PORT = 15721;
export const SWIXTER_PROXY_AUTH_TOKEN = "swixter-local-proxy";
export const SWIXTER_CLAUDE_MODEL = "SWIXTER_CLAUDE_MODEL";
export const SWIXTER_CLAUDE_HAIKU_MODEL = "SWIXTER_CLAUDE_HAIKU_MODEL";
export const SWIXTER_CLAUDE_SONNET_MODEL = "SWIXTER_CLAUDE_SONNET_MODEL";
export const SWIXTER_CLAUDE_OPUS_MODEL = "SWIXTER_CLAUDE_OPUS_MODEL";
